version: '3.1'
services:
    my-service: 
        build:
            context: .
        environment: 
            - SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN:-default}
            - SLACK_APP_TOKEN=${SLACK_APP_TOKEN:-default}
